### ISSUE TITLE
general keep_alive error

### ISSUE THREAD

**Issue by Upanc** [EmilAhmaBoy/simple-threaded-tcp#1]
attempted relative import beyond top-level package
Modify it like this
from sttcp import connections, screen_lock, print_sync
from sttcp.client import Client
from sttcp.server import Server

**Comment by EmilAhmaBoy** [comment]
Hello, @Upanc! Thanks for creating issue. I'll check it out soon.

**Comment by EmilAhmaBoy** [comment]
Oh I didn't update this project for a long time. Fixed. [PyPi](https://pypi.org/project/simple-threaded-tcp/).
